spring.application.name=InsightAI
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.jpa.hibernate.ddl-auto=update


github.api.base-url=https://api.github.com
spring.ai.anthropic.api-key=${anthropic.api-key}
spring.ai.anthropic.chat.options.model=claude-haiku-4-5
spring.ai.anthropic.chat.options.max-tokens=1024
spring.ai.anthropic.chat.options.temperature=0.7